#!/usr/bin/env php
<?php

use App\Commands\CommandController;
use App\Console\InputConsole;
use App\Console\InputValidator;
use App\Console\OutputConsole;
use App\Model\Fast;
use App\Store\StoreManager;

require_once './vendor/autoload.php';
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__, '.env');
$dotenv->load();

$commands = new CommandController(
    new InputConsole(),
    new OutputConsole(),
    new StoreManager(),
    new InputValidator(),
    new Fast()
);
$commands->run();



